[package]
name = "delta_compressor"
authors = ["Bennett G Sewell <bennett.sewell@bucketsofcrazy.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
hex-literal = "0.4.1"
once_cell = "1.19.0"
rand = "0.8.5"
regex = "1.10.2"
sha2 = "0.10.8"
